"""Alor adapter shells for the agent-operated MVP."""

from statarb.adapters.alor.auth import (
    AccessToken,
    AlorAuthConfig,
    AuthRefreshPolicy,
    TokenExchangeRequest,
    TokenLifecycleManager,
)
from statarb.adapters.alor.cws_orders import (
    CwsAuthorizeRequest,
    CwsCommandEnvelope,
    GuidFactory,
)
from statarb.adapters.alor.endpoints import (
    AlorEndpointCatalog,
    LIVE_ENDPOINT_CATALOG,
    TEST_ENDPOINT_CATALOG,
    get_endpoint_catalog,
)
from statarb.adapters.alor.http_market_data import (
    AlorAvailableBoardSnapshot,
    AlorHistoryBar,
    AlorObjectFormat,
    AlorQuoteSnapshot,
    AlorSecuritySnapshot,
    AvailableBoardsRequest,
    HistoricalBarsRequest,
    HttpRequestShape,
    QuotesSnapshotRequest,
    RecommendedStorageLayout,
    SecuritiesCatalogRequest,
    normalize_available_boards_response,
    normalize_history_response,
    normalize_quotes_response,
    normalize_securities_response,
    recommended_history_storage_layout,
    recommended_snapshot_storage_layout,
)
from statarb.adapters.alor.http_portfolio import (
    PortfolioOrdersRequest,
    PortfolioPositionsRequest,
    PortfolioRequest,
    PortfolioSummaryRequest,
    PortfolioTradesRequest,
)
from statarb.adapters.alor.mapper import (
    AlorPayloadMapper,
    CanonicalEventKind,
    CanonicalEventPlaceholder,
    MappingResult,
    MappingStatus,
    PlaceholderAlorMapper,
)
from statarb.adapters.alor.ws_market_data import (
    MarketDataSubscription,
    OrderBookSubscription,
    QuotesSubscription,
    WsRequestEnvelope,
)
from statarb.adapters.alor.ws_portfolio import (
    OrdersSubscription,
    PortfolioSubscription,
    PositionsSubscription,
    SummariesSubscription,
    TradesSubscription,
)

__all__ = [
    "AccessToken",
    "AlorAuthConfig",
    "AlorAvailableBoardSnapshot",
    "AlorHistoryBar",
    "AlorObjectFormat",
    "AlorEndpointCatalog",
    "AlorPayloadMapper",
    "AlorQuoteSnapshot",
    "AlorSecuritySnapshot",
    "AvailableBoardsRequest",
    "AuthRefreshPolicy",
    "CanonicalEventKind",
    "CanonicalEventPlaceholder",
    "CwsAuthorizeRequest",
    "CwsCommandEnvelope",
    "GuidFactory",
    "HistoricalBarsRequest",
    "HttpRequestShape",
    "LIVE_ENDPOINT_CATALOG",
    "MappingResult",
    "MappingStatus",
    "MarketDataSubscription",
    "OrderBookSubscription",
    "OrdersSubscription",
    "PlaceholderAlorMapper",
    "PortfolioSubscription",
    "PortfolioOrdersRequest",
    "PortfolioPositionsRequest",
    "PortfolioRequest",
    "PortfolioSummaryRequest",
    "PortfolioTradesRequest",
    "PositionsSubscription",
    "QuotesSubscription",
    "QuotesSnapshotRequest",
    "RecommendedStorageLayout",
    "SecuritiesCatalogRequest",
    "SummariesSubscription",
    "TEST_ENDPOINT_CATALOG",
    "TokenExchangeRequest",
    "TokenLifecycleManager",
    "TradesSubscription",
    "WsRequestEnvelope",
    "get_endpoint_catalog",
    "normalize_available_boards_response",
    "normalize_history_response",
    "normalize_quotes_response",
    "normalize_securities_response",
    "recommended_history_storage_layout",
    "recommended_snapshot_storage_layout",
]
